apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: flask-mongo-demo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: supersecret
  MONGO_USERNAME: appuser
  MONGO_PASSWORD: appsecret
  MONGO_AUTH_DB: admin