apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-mongo-demo
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80          # Port exposed inside the cluster
      targetPort: 5000  # Port inside container where Flask runs
      nodePort: 30001   # NodePort exposed on Minikube